### ISSUE TITLE
Using two fingers and changing or resetting the track while holding the skater causes various issues.

### ISSUE THREAD

**Issue by loganbraywork** [phetsims/energy-skate-park#192] opened 2020-02-07 23:58 UTC
<b>Test Device</b>

Ipad 6th generation

<b>Operating System</b>

IOS 13

<b>Browser</b>

Safari

<b>Problem Description</b>

For  https://github.com/phetsims/QA/issues/470

When the skater is held above the track using one finger and the track is switched via the radio button, the skater will automatically drop. Switching the track further causes a strange conservation of momentum. If the skater is allowed to exit the screen it will cause an overlap of the green and red return skater buttons. Same issue occurs if the reset button is hit.

<b>Steps to Reproduce</b>

1. Enter the Intro screen
2. Use one finger to hold the skater suspended over the track
3. Use a second finger to switch the track via the radio buttons on the right
4. Switch to another track using the radio buttons on the right, not letting go of the skater
5. If the skater has gained momentum lift finger and allow it to leave the screen
6. Observe the green and red return skater buttons

<b>Visuals</b>
![2020-02-7Sk8prk](https://user-images.githubusercontent.com/54685448/74074202-536b8c00-49ca-11ea-93b1-26c2f3d48c99.jpg)

![2020-02-07Sk8prkgifcutforgit](https://user-images.githubusercontent.com/54685448/74074337-dc82c300-49ca-11ea-9234-b30552751fb8.gif)

**Comment by jessegreenberg** [comment] 2020-02-09 23:42
When the scene changes, it is by design that the skater should return to ground.

```js
        // Reset the skater when the track is changed, see #179
        this.skater.returnToInitialPosition();
```

But it looks like the drag handler isn't interrupted for cases of multitouch,

**Comment by jessegreenberg** [comment] 2020-02-10 17:06
Fixed in the above commit, closing.

**Comment by loganbraywork** [comment] 2020-02-13 21:20
Just tested this in the published version Basics and it appears, so basics probably needs a maintenance release. Also appears for windows touch devices.

**Comment by jessegreenberg** [comment] 2020-02-14 22:20
Thanks @loganbraywork - confirmed this is happening on published version.

I would say it is up to @ariel-phet if a fix should be applied to energy-skate-park-basics 1.4 and a maintenance release deployed. https://github.com/phetsims/energy-skate-park/commit/c77ee6310e933d34130894a922602888ea58a12e (or something similar) could be done on the 1.4 branch of  energy-skate-park-basics.

**Comment by ariel-phet** [comment] 2020-02-17 18:52
@jessegreenberg - I think considering that lots has been refactored, the plan was to fully redeploy ESPB off master after ESP has been published. So I think full deployment is more appropriate than a maintenance release -- especially considering that such a bug has not been user reported.

**Comment by jessegreenberg** [comment] 2020-02-18 16:41
OK sounds good - since this has been fixed I will close and it will go out with energy-skate-park-basics republication off of master.

**Closed by jessegreenberg** 2020-02-18 16:41 UTC
Labels: type:bug, type:multitouch
