### ISSUE TITLE
Speedometer behind the energy graph

### ISSUE THREAD

**Issue by lmulhall-phet** [phetsims/energy-skate-park#106] opened 2019-08-12 21:54 UTC
**Test Device**

MacBook Air

**Operating System**

macOS 10.14.5

**Browser**

Chrome 76.0.3809.100

**Problem Description**

For https://github.com/phetsims/QA/issues/397. In the "Graphs" screen, the speedometer is stuck behind the energy graph. Part of the speedometer is cut off by the energy graph. The energy graph is open by default, so by default it looks like checking the speedometer checkbox doesn't do anything.

**Visuals**

![Screen Shot 2019-08-12 at 3 41 51 PM](https://user-images.githubusercontent.com/31285590/62900709-17f04d80-bd18-11e9-9c10-996fe0b8da8d.png)

<details>
<summary><b>Troubleshooting Information</b></summary>
!!!!! DO NOT EDIT !!!!!
Name: ‪Energy Skate Park‬
URL: https://phet-dev.colorado.edu/html/energy-skate-park/1.0.0-dev.4/phet/energy-skate-park_all_phet.html
Version: 1.0.0-dev.4 2019-08-07 21:12:37 UTC
Features missing: touch
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.100 Safari/537.36
Language: en-US
Window: 1440x821
Pixel Ratio: 1/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 15 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 80)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {}
</details>

**Comment by arouinfar** [comment] 2019-08-30 20:21
Thanks @lmulhall-phet this is a duplicate of #88, so I'll move your comment to that issue and close.

**Closed by arouinfar** 2019-08-30 20:21 UTC
Labels: type:bug
