### ISSUE TITLE
CT: Thermal energy should be non-negative

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/energy-skate-park#62] opened 2019-02-22 15:36 UTC
```
energy-skate-park : fuzz : require.js : run
Query: brand=phet&ea&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed: Thermal energy should be non-negative: skaterState: [object Object], initialEnergy: -0.00005207941861758813, proposedPosition: Vector2(-4.169999851919449, 0), proposedVelocity: Vector2(4.606722152830063e-17, -0.016666666666666666), dt: 0.016666666666666666, newSpeed: 4.606722152830063e-17, newKineticEnergy: 5.570745860761002e-32, newPotentialEnergy: 0, newThermalEnergy: -0.00005207941861758813, referenceHeight: 0, tracked in https://github.com/phetsims/energy-skate-park/issues/45
Error: Assertion failed: Thermal energy should be non-negative: skaterState: [object Object], initialEnergy: -0.00005207941861758813, proposedPosition: Vector2(-4.169999851919449, 0), proposedVelocity: Vector2(4.606722152830063e-17, -0.016666666666666666), dt: 0.016666666666666666, newSpeed: 4.606722152830063e-17, newKineticEnergy: 5.570745860761002e-32, newPotentialEnergy: 0, newThermalEnergy: -0.00005207941861758813, referenceHeight: 0, tracked in https://github.com/phetsims/energy-skate-park/issues/45
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1550801073070/assert/js/assert.js:22:13)
    at LabModel.switchToGround (https://bayes.colorado.edu/continuous-testing/snapshot-1550801073070/energy-skate-park/js/energy-skate-park/common/model/EnergySkateParkModel.js?bust=1550838902483:495:17)
    at LabModel.stepFreeFall (https://bayes.colorado.edu/continuous-testing/snapshot-1550801073070/energy-skate-park/js/energy-skate-park/common/model/EnergySkateParkModel.js?bust=1550838902483:530:21)
    at LabModel.stepTrack (https://bayes.colorado.edu/continuous-testing/snapshot-1550801073070/energy-skate-park/js/energy-skate-park/common/model/EnergySkateParkModel.js?bust=1550838902483:992:21)
    at LabModel.stepModel (https://bayes.colorado.edu/continuous-testing/snapshot-1550801073070/energy-skate-park/js/energy-skate-park/common/model/EnergySkateParkModel.js?bust=1550838902483:1302:39)
    at LabModel.step (https://bayes.colorado.edu/continuous-testing/snapshot-1550801073070/energy-skate-park/js/energy-skate-park/common/model/EnergySkateParkModel.js?bust=1550838902483:400:31)
    at first (https://bayes.colorado.edu/continuous-testing/snapshot-1550801073070/joist/js/Sim.js?bust=1550838902483:217:24)
    at Emitter.emit (https://bayes.colorado.edu/continuous-testing/snapshot-1550801073070/axon/js/Emitter.js?bust=1550838902483:251:55)
    at EnergySkateParkSim.stepSimulation (https://bayes.colorado.edu/continuous-testing/snapshot-1550801073070/joist/js/Sim.js?bust=1550838902483:920:34)
    at EnergySkateParkSim.stepOneFrame (https://bayes.colorado.edu/continuous-testing/snapshot-1550801073070/joist/js/Sim.js?bust=1550838902483:901:14)
id: Bayes Chrome
Approximately 2/21/2019, 7:04:33 PM
energy-skate-park : phet-io-tests : assert
7 out of 7 tests passed. 0 failed.

Approximately 2/21/2019, 7:04:33 PM
energy-skate-park : phet-io-tests : no-assert
7 out of 7 tests passed. 0 failed.

Approximately 2/21/2019, 7:04:33 PM
```

**Comment by KatieWoe** [comment] 2019-04-04 14:51
```
energy-skate-park-basics : fuzz : require.js : run
Query: brand=phet&ea&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed: Thermal energy should be non-negative: skaterState: [object Object], initialEnergy: -0.0001994617083890646, proposedPosition: Vector2(-5.24507752703119, 0), proposedVelocity: Vector2(1.000094796674526e-17, -0.16333333333333333), dt: 0.016666666666666666, newSpeed: 1.000094796674526e-17, newKineticEnergy: 1.250237002919327e-33, newPotentialEnergy: 0, newThermalEnergy: -0.0001994617083890646, referenceHeight: 0, tracked in https://github.com/phetsims/energy-skate-park/issues/45
Error: Assertion failed: Thermal energy should be non-negative: skaterState: [object Object], initialEnergy: -0.0001994617083890646, proposedPosition: Vector2(-5.24507752703119, 0), proposedVelocity: Vector2(1.000094796674526e-17, -0.16333333333333333), dt: 0.016666666666666666, newSpeed: 1.000094796674526e-17, newKineticEnergy: 1.250237002919327e-33, newPotentialEnergy: 0, newThermalEnergy: -0.0001994617083890646, referenceHeight: 0, tracked in https://github.com/phetsims/energy-skate-park/issues/45
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1554350814967/assert/js/assert.js:22:13)
    at PlaygroundModel.switchToGround (https://bayes.colorado.edu/continuous-testing/snapshot-1554350814967/energy-skate-park/js/energy-skate-park/common/model/EnergySkateParkModel.js?bust=1554371800952:493:17)
    at PlaygroundModel.stepFreeFall (https://bayes.colorado.edu/continuous-testing/snapshot-1554350814967/energy-skate-park/js/energy-skate-park/common/model/EnergySkateParkModel.js?bust=1554371800952:528:21)
    at PlaygroundModel.stepTrack (https://bayes.colorado.edu/continuous-testing/snapshot-1554350814967/energy-skate-park/js/energy-skate-park/common/model/EnergySkateParkModel.js?bust=1554371800952:990:21)
    at PlaygroundModel.stepModel (https://bayes.colorado.edu/continuous-testing/snapshot-1554350814967/energy-skate-park/js/energy-skate-park/common/model/EnergySkateParkModel.js?bust=1554371800952:1300:39)
    at PlaygroundModel.step (https://bayes.colorado.edu/continuous-testing/snapshot-1554350814967/energy-skate-park/js/energy-skate-park/common/model/EnergySkateParkModel.js?bust=1554371800952:398:31)
    at first (https://bayes.colorado.edu/continuous-testing/snapshot-1554350814967/joist/js/Sim.js?bust=1554371800952:213:24)
    at Emitter.emit (https://bayes.colorado.edu/continuous-testing/snapshot-1554350814967/axon/js/Emitter.js?bust=1554371800952:280:55)
    at EnergySkateParkBasicsSim.stepSimulation (https://bayes.colorado.edu/continuous-testing/snapshot-1554350814967/joist/js/Sim.js?bust=1554371800952:916:34)
    at EnergySkateParkBasicsSim.stepOneFrame (https://bayes.colorado.edu/continuous-testing/snapshot-1554350814967/joist/js/Sim.js?bust=1554371800952:897:14)
id: Bayes Chrome
Approximately 4/3/2019, 10:06:54 PM
energy-skate-park-basics : phet-io-tests : assert
7 out of 7 tests passed. 0 failed.

Approximately 4/3/2019, 10:06:54 PM
energy-skate-park-basics : phet-io-tests : no-assert
7 out of 7 tests passed. 0 failed.

Approximately 4/3/2019, 10:06:54 PM
```

**Comment by jessegreenberg** [comment] 2019-05-23 15:09
This is a duplicate of https://github.com/phetsims/energy-skate-park/issues/45

**Closed by jessegreenberg** 2019-05-23 15:09 UTC
Labels: type:automated-testing
