### ISSUE TITLE
Can we eliminate WebGL from Energy Skate Park?

### ISSUE THREAD

**Issue by samreid** [phetsims/energy-skate-park#42] opened 2018-12-03 16:04 UTC
Energy Skate Park: Basics was developed with the goal to have fast and smooth performance on iPad 2 without any pausing or hiccups.  That constraint led us to several more costly implementation strategies, such as rearranging layers in order to put all animated components together in a single WebGL layer.  These implementation approaches have been in discussion lately for example in https://github.com/phetsims/griddle/issues/32 where we discussed it griddle should be written in such a way to make it easier to split up rendering into webgl vs non-webgl layers.  It has also let to questions in issues such as https://github.com/phetsims/energy-skate-park/issues/40 where it seems like layer splitting is causing performance issues.

Also, we have discussed moving to iPad 4 or iPad Air as our target platform for performance tuning.

Would it be in the best long-term interest of this simulation to remove its usage of WebGL--eliminate the complexities regarding layering that were implemented to put all animated components into a single WebGL layer--and test performance on iPad 4 or iPad Air to see if it is fast enough without WebGL?  Assigning to @jessegreenberg for initial thoughts, but this will likely need to be discussed with @ariel-phet as well.

**Comment by jessegreenberg** [comment] 2018-12-03 16:57
This would certainly help with maintainability in the long run, and development in the short run. For example a number of webgl considerations have come up recently because of this like #40 #39 #38 #31 #25, https://github.com/phetsims/energy-skate-park/issues/20#issuecomment-431005392. And others will come up as more is added to ESP.

But I would also think that the webgl work would improve performance on more than just iOS tablets, so if we remove the webgl rendering shouldn't we test on all supported platforms?

At a meeting a couple of weeks ago I recall @ariel-phet saying that we were considering dropping ipad2 support or not making it our "performance target", but that we weren't there yet. So I think it depends on where we are with this decision.

**Comment by jessegreenberg** [comment] 2018-12-07 23:04
@ariel-phet can you please comment on the above? This will require QA time to test performance without WebGL, and depends on the timeline for PhET reducing support for iPad2.

**Comment by ariel-phet** [comment] 2018-12-10 17:34
@jessegreenberg @samreid when the latest version of the iOS PhET app is published (1.2), we plan to drop "official support" for iPad2. The new iOS PhET app will be restricted to run on iOS 10.3 and higher, and since iPad2 cannot be upgraded to iOS 10, the app will effectively not support iPad2. We expect the app to be published soon, it is in the final stages of QA. It could be as soon as the next week or two, but by sometime in January is almost definite.

When the 1.2 of the app is published, we will change requirements on our website, and QA will be instructed to still test on iPad2, but in the same way we for a long time tested on iPad3, which was to help see if there were some obvious performance issues. We still want the sims to open on iPad2 and function, but we will move to a place where we allow degraded performance. 

If you two feel it would be best to remove WebGL, that is fine, bearing in mind that this is a flagship sim that we will expect to have excellent performance on our most popular platforms (like chomebook and iPad air).

**Comment by samreid** [comment] 2018-12-10 23:51
> If you two feel it would be best to remove WebGL, that is fine

I agree with @jessegreenberg's first paragraph in https://github.com/phetsims/energy-skate-park/issues/42#issuecomment-443783955 that removing the many simulation-specific WebGL parts will make this simulation easier to develop and maintain in both the short and long term.  

I tried running the requirejs version of energy skate park on the iPad Air with webgl=false and saw very good performance during animation--very smooth and no hiccups or hitches.  However, I noted one problem which may throw a wrench into this idea.  When dragging the skater slightly offscreen so that some SVG graphics were partly offscreen, the performance significantly declined.  We saw this same problem years ago during initial development of Energy Skate Park: Basics.  To be specific, Animation in the potential well runs at 60fps on iPad AIr with ?webgl=false and all checkmarks checked, but dragging the skater partway off the top of the screen and releasing drops the frame rate to around 30fps (and very sluggish) until the skater + pie chart is fully on screen, then it speeds up again.  This issue was documented and explored in https://github.com/phetsims/scenery/issues/270

Here are some possible ways to proceed:
1. Stick with sim-specific custom WebGL hacks in ESP (increases development maintenance costs, but has good performance and no odd "edge case" performance concerns)
2. Eliminate WebGL from the simulation and live with this laggy edge case behavior on iPads (not desirable because the motion on the edge of the screen seems non-smooth and nonphysical)
3. Eliminate WebGL from the simulation and work around the laggy edge behavior (such as not allowing the user to drag the skater off the screen)
4. Try to solve https://github.com/phetsims/scenery/issues/270 first, if it can be solved then eliminate WebGL from Energy Skate Park.
5. Go "all in" on WebGL and fix other scenery components such as text and shapes to use WebGL.  This will also eliminate the need for simulation-specific hacks and workarounds for sims like Energy Skate Park (we would be able to use regular scenery Nodes), and will maintain high performance and correct behavior on the edge of the screen.  This will incur a significant up-front cost for scenery webgl development, and some recurring cost going forward as we maintain WebGL in scenery.  Some notes are documented here: https://github.com/phetsims/scenery/issues/303

Also, I have not tested at all on chromebook--we should probably request a test on that before deciding which way to go.

**Comment by samreid** [comment] 2018-12-10 23:57
@ariel-phet any thoughts on the preceding comment?  Should I set up a QA issue for preliminary chromebook performance testing?

**Comment by jessegreenberg** [comment] 2019-01-24 20:23
I only have access to an iPad2, but tried to reproduce what @samreid reported in
> When dragging the skater slightly offscreen so that some SVG graphics were partly offscreen, the performance significantly declined.

Indeed, I noticed this too with `webgl=false`. On iPad2 without webgl, the skater animates very slowly when moving on its own. But dragging the skater is very fast (except for at the edges).

However, I tried `renderer= null` on the ScreenView and `renderer='canvas'` just on the skater, and all dragging was fast around the edges of the screen (though other skater animation was still slow). Maybe this could be an acceptable workaround if we can't work on https://github.com/phetsims/scenery/issues/270.

Anyway, Ill make an issue to test performance on chromebooks and our slowest platforms.

**Comment by jessegreenberg** [comment] 2019-01-24 20:41
@samreid I made https://github.com/phetsims/QA/issues/266 for the request, feel free to add any other details if you think I missed anything.

**Comment by jessegreenberg** [comment] 2019-04-17 18:37
https://github.com/phetsims/QA/issues/266 is complete and the results are summarized in a table here:
https://github.com/phetsims/QA/issues/266#issuecomment-462510121

To summarize: The sim generally performs the same with/without WebGL. There are two exceptions. First, WebGL in Edge WebGL is substantially *slower* than without. This might change soon with the Edge switch to Chromium. Second, when WebGL is disabled we observed the issue @samreid mentioned in both iOS 11 and iOS 12.
>  When dragging the skater slightly offscreen so that some SVG graphics were partly offscreen, the performance significantly declined.

**Comment by jessegreenberg** [comment] 2019-04-18 21:10
We discussed a bit in https://github.com/phetsims/scenery/issues/270. To summarize, we can't dive into that issue yet and it is unclear whether there is anything we can do as it may be a Safari problem. And we can't invest more in general WebGL support yet.

First, we should explore another alternative for this simulation that may address all concerns: Use SVG generally, but render objects that go off screen with canvas (or maybe WebGL if they can all be in a single layer).

This would hopefully keep animation fluid on iOS as things move off screen, remove most of the complicated layering code in EnergySkateParkScreenView, and support animation outside of the WebGL layer.

**Comment by jessegreenberg** [comment] 2019-04-18 21:33
The check box that slows the skater down the most when off screen is the "Grid" checkbox.

**Comment by jessegreenberg** [comment] 2019-04-18 21:38
The off-screen slowdown goes away almost entirely when everything is rendered in SVG except for the `BarGraphForeground`, I wonder why that is.

**Comment by jessegreenberg** [comment] 2019-04-22 15:22
After https://github.com/phetsims/energy-skate-park/issues/42#issuecomment-484698634 and https://github.com/phetsims/QA/issues/266 we expect the following changes on various platforms after removing the custom WebGL from this sim:

- Equivalent performance on Win 10 Chrome
- Better performance on Edge/IE11 (at least until the Chromium switch)
- Equivalent performance on Chromebooks
- ~60fps on iPad Air 2 iOS 12, including when skater is out of screen
- Much slower on iPad2 (10-15 fps) (T2he fixed time step in this sim makes it look like it is running in very  slow motion).

@ariel-phet @samreid do you we have enough info to make a decision? If we can continue without WebGL development will be much faster, but the sim won't be usable on iPad 2. We will keep a high frame rate everywhere else.

**Comment by samreid** [comment] 2019-04-22 15:29
To me, it sounds appropriate to eliminate WebGL-related code and workarounds from Energy Skate Park.

**Comment by ariel-phet** [comment] 2019-04-22 20:38
@jessegreenberg now that we have made the decision to no longer support iPad2 officially, we must accept that some sims will have significant performance issues on that platform. 

Given what you lay out in terms of performance in https://github.com/phetsims/energy-skate-park/issues/42#issuecomment-485448030 I think removing WebGL is totally acceptable.

**Comment by jessegreenberg** [comment] 2019-04-23 15:34
Thanks @ariel-phet and @samreid,  then we will proceed with #66 and remove the custom WebGL from this code from this sim. Closing this issue since we will continue there.

**Closed by jessegreenberg** 2019-04-23 15:34 UTC
Labels: type:performance, type:question
