### ISSUE TITLE
Data point on Measure screen behaves oddly when skater is standing still

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/energy-skate-park#310] opened 2020-11-16 22:28 UTC
**Test device**
MacBook Air
**Operating System**
Mac 10.15.7
**Browser**
Chrome
**Problem description**
For https://github.com/phetsims/QA/issues/578
When the skater is sitting still on the ground on the measurement screen, the data point there appears and disappears quickly, leading to an odd flickering when trying to take a measurement of it. It does not do this when paused. If this is expected/not an issue feel free to close. Seems minor to me and probably doesn't need to be addressed for the release either way.

**Visuals**
![flashingdatapoint](https://user-images.githubusercontent.com/41024075/99315499-fa196e80-281f-11eb-94dc-f651b70b427d.gif)

**Comment by arouinfar** [comment] 2020-11-17 01:12
Nice find @KatieWoe.

While I agree it's somewhat minor, this looks pretty buggy to me. It's not the most important use of the probe, but it's also not an unrealistic use case. It seems like the dot might be constantly redrawing itself which is why things flicker when the sim isn't paused. 

We'll be revisiting this simulation for phet-io (though it's not a top iO priority right now) so we could defer and fix it then. @ariel-phet what do you think?

**Comment by ariel-phet** [comment] 2020-11-17 01:59
@arouinfar @jessegreenberg I can reproduce this bug on Win 10 (trying on FF, but guessing it is general)

Steps to reproduce for me:
1. Go to measure screen
2. Place the probe on the skater on the ground (should work on this first try)
3. Remove the probe and replace on the data point 
4. On putting the probe back on the data point it will flicker and not allow a reading (sometimes on the first try sometimes you need to read and take a 3rd try to see the flicker)

Since I can reproduce this bug easily and a fundamental learning goal in this sim centers around adjusting the reference height and seeing how potential energy changes, I think we must fix this bug for the initial release.

@jessegreenberg I could be totally wrong by my intuition tells me there is some kind of interaction going on between the reading of the probe and the fact the probe is set to have its bounds not dip below the ground. Just a hunch.

**Comment by jessegreenberg** [comment] 2020-11-17 19:06
Yes, thanks for finding @KatieWoe. I think it also has to do with the data points being removed over time. While the skater is on the ground data points are being added and removed just like they would be if he were on the track. This doesn't happen to me right on sim load. But with the same initial conditions, if I wait about 10 seconds and then try to measure the data point this starts to happen.

**Comment by jessegreenberg** [comment] 2020-11-17 22:54
This should be fixed by the above commit. @KatieWoe can you please verify on master?

**Comment by KatieWoe** [comment] 2020-11-17 23:29
Looks good on master

**Comment by jessegreenberg** [comment] 2020-11-19 04:22
OK thanks @KatieWoe, moved to release branch.

**Comment by jessegreenberg** [comment] 2020-11-19 04:45
@arouinfar by the way, this fix also addressed the issue mentioned in #298 
> The sensor doesn't detect a hit with a data point unless it is being dragged. So when the new data point goes under the crosshairs it's information is not displayed.

It now updates as points are moved below the sensor.

**Comment by brooklynlash** [comment] 2020-11-19 17:13
Looks as if it is fixed on rc4, Windows 10

**Comment by jessegreenberg** [comment] 2020-11-23 23:53
Thanks @brooklynlash! Closing this issue.

**Comment by KatieWoe** [comment] 2020-12-07 18:39
One quick thing I noticed. If there is thermal energy and you clear it, the point does not update. Assigning @arouinfar as well to determine if this is an issue.
![thermalclear](https://user-images.githubusercontent.com/41024075/101390934-ce1e6580-3880-11eb-94ae-4cb7f02684fa.gif)
Linking issue: https://github.com/phetsims/QA/issues/579

**Comment by arouinfar** [comment] 2020-12-07 19:40
> One quick thing I noticed. If there is thermal energy and you clear it, the point does not update. 

This is true regardless of whether the skater is on the ground or not. The data points represent the state of the sim when the point was created, and do not retroactively change. The same occurs if you change the gravity mid-way through the skater's path. The dots drawn before the gravity was changed display values with the old value of gravity. 

I don't think there's anything to do here, other than make sure the behavior of the dots is clear in the Teacher Tips, so tagging #147 and closing.

**Closed by arouinfar** 2020-12-07 19:40 UTC
Labels: priority:2-high, status:ready-for-qa, type:bug
