### ISSUE TITLE
Text in some Preferences tabs doesn't change with ?stringTest=

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/energy-skate-park#366] opened 2023-01-09 18:49 UTC
**Test device**
iPad and MacBook air

**Operating System**
iOS 16.1.1 and macOS 13.1

**Browser**
safari

**Problem description**
For https://github.com/phetsims/qa/issues/870, when testing with ?stringTest= , the text under the Simulation and Localization tabs doesn't change. 

**Visuals**
Some examples:
<img width="608" alt="Screenshot 2023-01-09 at 1 46 03 PM" src="https://user-images.githubusercontent.com/87318828/211384523-61e22935-ed4d-4699-ab68-6454eb529502.png">
<img width="607" alt="Screenshot 2023-01-09 at 1 46 16 PM" src="https://user-images.githubusercontent.com/87318828/211384543-bf3088e8-d56d-46fe-bce1-83fbdf18cdff.png">
<img width="514" alt="Screenshot 2023-01-09 at 1 46 58 PM" src="https://user-images.githubusercontent.com/87318828/211384558-e47e6ca8-57e8-4456-b27d-74dd5013899a.png">

<details>
Troubleshooting information:
!!!!! DO NOT EDIT !!!!!
Name: ‪Energy Skate Park‬
URL: https://phet-dev.colorado.edu/html/energy-skate-park/1.2.0-rc.1/phet/energy-skate-park_all_phet.html
Version: 1.2.0-rc.1 2022-12-22 16:17:42 UTC
Features missing: applicationcache, applicationcache, touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36
Language: en-US
Window: 1475x780
Pixel Ratio: 1.7999999523162842/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 31 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {}
</details>

**Comment by AgustinVallejo** [comment] 2023-01-09 18:51
@marlitas Do you think this is more on the side of Preferences Dialog or would be a Sim issue?

**Comment by samreid** [comment] 2023-01-10 16:21
I also reproduced this problem.  The Region and Culture combo box is defined in Joist.  There is a note in RegionAndCultureComboBox.ts:

```ts
// Not translatable until design is complete, see https://github.com/phetsims/energy-skate-park/issues/345
const regionAndCultureString = 'Region and Culture';
```

**Comment by marlitas** [comment] 2023-01-10 18:41
Hmmm... based on that comment it seems like I shouldn't update the dialog... but design is complete for that issue... not sure if the comment is referencing ESP design complete or preferences dialog design is complete... seems strange to me that we wouldn't translate it though. @arouinfar thoughts?

**Comment by arouinfar** [comment] 2023-01-10 19:33
@marlitas @AgustinVallejo I think the code comment is referring to the ESP design since it references https://github.com/phetsims/energy-skate-park/issues/345. That issue is now closed, so it's safe to make the string translatable. In general, we shouldn't publish a simulation with untranslatable strings.

**Comment by marlitas** [comment] 2023-01-10 19:34
That makes a lot of sense. @AgustinVallejo I'll address this today then!

**Comment by marlitas** [comment] 2023-01-10 23:11
Changes made and pushed up. @AgustinVallejo up to you for review and any further work!

**Comment by Nancy-Salpepi** [comment] 2023-01-12 22:28
The acceleration units text in the Simulation Tab still hasn't been changed. 
<img width="465" alt="Screenshot 2023-01-12 at 5 26 58 PM" src="https://user-images.githubusercontent.com/87318828/212194402-44a8268e-3900-4f96-8b27-b8d12bf49217.png">
<img width="465" alt="Screenshot 2023-01-12 at 5 27 26 PM" src="https://user-images.githubusercontent.com/87318828/212194419-75a68b7a-a0f3-431c-ac68-985c8dfc3fdc.png">

**Comment by arouinfar** [comment] 2023-01-13 00:05
Bummer, looks like we missed the Acceleration Units. That string definitely needs to be translatable @AgustinVallejo.

**Comment by marlitas** [comment] 2023-01-13 00:41
Oh no... Sorry! That was definitely my oversight. 🤦‍♀️ I'll do it now.

**Comment by marlitas** [comment] 2023-01-13 00:54
Changes pushed. Confirming, we only are internationalizing "Acceleration Units" right? Not "m/s^2" or "N/kg"?

**Comment by AgustinVallejo** [comment] 2023-01-13 00:56
Should I then cherry pick this commit and deploy another rc?

**Comment by KatieWoe** [comment] 2023-01-13 22:41
I'm still seeing the units issue in rc.3
![units](https://user-images.githubusercontent.com/41024075/212432307-ca185599-b7e8-4583-82fe-c665de25ee89.png)

**Comment by arouinfar** [comment] 2023-01-13 23:06
@KatieWoe the units themselves are not translatable. What should be translatable is the label "Acceleration Units" which now is doubled with the `stringTest` so I think this issue is good to go.

**Comment by KatieWoe** [comment] 2023-01-13 23:14
Ok. Thanks for the clarification. But isn't it translatable in the sim?
![translate](https://user-images.githubusercontent.com/41024075/212435690-ff8eabf7-3e19-4708-a58e-122de0aebd73.png)

**Comment by arouinfar** [comment] 2023-01-13 23:39
I think `stringTest` can be a bit wonky with how it displays in sims, so I decided to check the translation utility. I found these entries, so it seems like the units actually are translatable. 
<img width="937" alt="image" src="https://user-images.githubusercontent.com/8419308/212437465-605b0125-ac0b-4e99-85c2-de234783082c.png">

In practice, I don't know if these units are ever actually translated. However, if they're translatable in the Gravity Control, they need to be translatable in the Preferences dialog.

Back to @marlitas and @AgustinVallejo.

**Comment by marlitas** [comment] 2023-01-14 00:06
Oh dear... I was worried about that above. I can get to this tonight.

**Comment by arouinfar** [comment] 2023-01-14 00:22
Sorry about that @marlitas. I didn't see it until it was too late. 🙁

**Comment by marlitas** [comment] 2023-01-17 05:05
I internationalized the units in preferences, however when I was using `stringTest=dynamic` I hit an assertion: `Assertion failed:  preferredWidth should be null or a non-negative finite number`. Analyzing the stack it seems this is coming from a comboBox. Through some testing I've determined this is the RegionAndCultureComboBox. 

To reproduce:
1. Load sim with `stringTest=dynamic`
2. open preferencesPanel
3. hit up arrow twice (stride 2)

I checked to see if this bug existed with or without the commit I made above, and it's still happening either way... I don't think dynamicStringTest is a 100% reliable way of replicating translation behavior, but I also haven't narrowed down wether the source of the bug is dynamicStringTest, the string it's trying to process, or the comboBox itself.

I also tried to run the sim with `locales=*` and no dynamic locales came up... so maybe dynamic layout isn't a concern here?

@arouinfar, @AgustinVallejo, @Nancy-Salpepi  thoughts?

**Comment by samreid** [comment] 2023-01-17 15:08
The combo box is requesting a negative preferred width.  Here is a guard that could prevent it:

<details>

```diff

Subject: [PATCH] Guard preferred width, see https://github.com/phetsims/energy-skate-park/issues/366
---
Index: js/ComboBox.ts
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/js/ComboBox.ts b/js/ComboBox.ts
--- a/js/ComboBox.ts	(revision 667c1e8b0c22b3289db82bc771a0266232783661)
+++ b/js/ComboBox.ts	(date 1673967971646)
@@ -283,9 +283,10 @@
         options.labelNode.boundsProperty
       ], ( localPreferredWidth, labelBounds ) => {
         // If we don't have a preferred width, we'll forward that to our button
-        return localPreferredWidth === null ?
-               null :
-               localPreferredWidth - labelBounds.width - options.labelXSpacing;
+        const preferredWidth = localPreferredWidth === null ?
+                               null :
+                               Math.max( 0, localPreferredWidth - labelBounds.width - options.labelXSpacing );
+        return preferredWidth;
       }, {
         reentrant: true
       } ) :

```

</details>

@marlitas or @jonathanolson does this seem like a good guard to you?

**Comment by marlitas** [comment] 2023-01-17 17:18
@samreid and @jonathanolson I would be interested in jumping in to that 11:00 MT call today if possible.

**Comment by samreid** [comment] 2023-01-17 18:35
@marlitas and I discussed it, and we found that changing `const contentNode = new VBox( {` to `new Node` in LocalizationPreferencesPanel prevents the problem.  We feel that as long as the options can pass in an arbitrary label then this code in ComboBox is subject to going negative, unless localPreferredWidth is somehow supposed to get smaller when the label gets bigger:

```ts
    // We'll need to adjust our button's preferred width if we have a label
    const buttonPreferredWidthProperty =
      options.labelNode ?
      new DerivedProperty( [
        this.localPreferredWidthProperty,
        options.labelNode.boundsProperty
      ], ( localPreferredWidth, labelBounds ) => {
        // If we don't have a preferred width, we'll forward that to our button
        return localPreferredWidth === null ?
               null :
               localPreferredWidth - labelBounds.width - options.labelXSpacing;
      }, {
        reentrant: true
      } ) :
      this.localPreferredWidthProperty;
```

So without @jonathanolson's expertise, we would probably proceed with a Math.max guard in this code, but we still want to understand if there is an upstream problem or if this would be masking underlying trouble.  Let's discuss with @jonathanolson.

**Comment by samreid** [comment] 2023-01-17 19:06
@jonathanolson and @marlitas and I fixed the immediate problem in that commit. It should be cherry-pickable via that commit to the sun repo.  @AgustinVallejo can you take the lead on cherry-picking that and next steps?  Thanks!

**Comment by AgustinVallejo** [comment] 2023-01-17 19:07
Right away!

**Comment by AgustinVallejo** [comment] 2023-01-17 19:59
Cherry-picked. Please close this issue when completed

**Comment by KatieWoe** [comment] 2023-01-17 22:53
The units don't seem translatable in this version still. Am I correct that they should be now?
<img width="600" alt="notworking" src="https://user-images.githubusercontent.com/41024075/213029830-bb4abc05-48c3-4ec7-9745-4005ee36489e.png">

**Comment by arouinfar** [comment] 2023-01-17 23:02
@AgustinVallejo was https://github.com/phetsims/energy-skate-park/commit/a13bdd389a3c3aa11ad2e27d770e9ea411b5a23f included in the commits you cherry-picked?

**Comment by AgustinVallejo** [comment] 2023-01-17 23:06
Apparently not! My bad, will fix

**Comment by KatieWoe** [comment] 2023-01-18 16:36
Looks good in rc.5

**Closed by KatieWoe** 2023-01-18 16:36 UTC
Labels: type:bug, type:i18n
