### ISSUE TITLE
Wrapper Unit Tests: createTandem cannot accept dots, Property already deferred

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/energy-skate-park#68] opened 2019-04-26 16:48 UTC
While debugging #67 I am encountering these when running wrapper unit tests.
> ncaught Error: Assertion failed: createTandem cannot accept dots: energySkatePark.labScreen.labModel.controlPoint.element~0.sourcePositionProperty

And 

>  Assertion failed: Property already deferred

I am curious about the first error. "element" is not defined as a tandem name in the sim, so is "controlPoint.element~0" getting generated internally?

I ran ?fuzz with studio and I am not sure how else I can try to reproduce outside of unit tests. @samreid @chrisklus or @zepumph would you mind helping with these?

**Comment by zepumph** [comment] 2019-05-09 18:25
I can reproduce this by loading the state wrapper.

**Comment by zepumph** [comment] 2019-05-09 22:00
Bugs I've cleaned up in this issue (sorry they all sorta mixed together):

* A few instances of `phetioEngine.hasInstance` weren't renamed to `phetioEnging.hasPhetioObject`
* many NodeIO subproperties were added to the state when we worked on (https://github.com/phetsims/phet-io/issues/1420). In general this was planned, but for dynamic Nodes, we didn't want the sub Properties in the state at all, (most of the time the nodes were sub elements of a dynamic node that was dependent on a dynamic model element). Commits coming in for multiple sims here.
* `createTandem cannot accept dots` assertion was fixed by adding `createFromPhetioID`, see https://github.com/phetsims/phet-io/issues/1442 for more info (because we overhauled Tandem as part of that issue) and I will link those commits over there too. I marked it as deprecated because I don't want people just using it before we know that it is a good pattern. I am treating it as a holdover right now.
* I also changed the GroupTandem structure back from before we prototyped with it for new dynamic elements (Group.js stuff).

@samreid I'm going to assign you to review, but ideally we should just have a conversation about this stuff. I think it will be much easier than trying to parse each thing above over comment chat.

**Comment by samreid** [comment] 2019-05-30 22:32
Reducing priority relative to other high priority tasks.

**Comment by samreid** [comment] 2020-04-25 17:11
Unassigning until we turn our attention to phet-io for this sim.

**Comment by pixelzoom** [comment] 2021-02-19 18:58
I'm not clear on what the status is for this issue.  It's ready-for-review but unassigned.    Looks like @zepumph did the bulk of the work as described in https://github.com/phetsims/energy-skate-park/issues/68#issuecomment-491083944.  So back to him to adjust labels and describe what remains to be done.

**Comment by zepumph** [comment] 2021-02-26 03:37
This older pattern of dynamic elements, and therefore need to create a hacky Tandem, was removed in https://github.com/phetsims/tandem/issues/87. 

There are no more usages of `createFromPhetioID`

CLosing

**Closed by zepumph** 2021-02-26 03:37 UTC
Labels: dev:phet-io, status:ready-for-review
