### ISSUE TITLE
Not everything is reset

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/energy-skate-park#300] opened 2020-10-19 20:47 UTC
**Test device**
MacBook Air
**Operating System**
Mac OS 10.15.7
**Browser**
Chrome 86.0.4240.80
**Problem description**
For https://github.com/phetsims/QA/issues/544
When the orange reset all button is used, not everything resets. The skater selection and the path checkbox are the two I have seen. Found on first screen, but the skater selection appears elsewhere and has the bug there as well.
**Steps to reproduce**
1. Load the sim and go to the first screen.
2. Turn on the path checkbox
3. Change the skater
4. Hit the reset all button

**Visuals**
https://drive.google.com/file/d/1tt0bCmjdGsnVK9_IEt90YD-GsoZHHKQR/view?usp=sharing

Troubleshooting information:

<details>

!!!!! DO NOT EDIT !!!!!
Name: ‪Energy Skate Park‬
URL: https://phet-dev.colorado.edu/html/energy-skate-park/1.1.0-rc.1/phet/energy-skate-park_all_phet.html
Version: 1.1.0-rc.1 2020-09-02 16:48:45 UTC
Features missing: applicationcache, applicationcache, touch
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.80 Safari/537.36
Language: en-US
Window: 1294x685
Pixel Ratio: 1/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 15 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 80)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {}

</details>

**Comment by KatieWoe** [comment] 2020-10-22 20:20
I think the path checkbox may actually start checked, so it might not be an issue.

**Comment by arouinfar** [comment] 2020-10-22 21:28
Thanks @KatieWoe. It looks like the issue is limited to the skater selection and the Path checkbox. Both should revert back to the default, which is skater 1 (the one wearing the PhET sweater) and Path off.

**Comment by jessegreenberg** [comment] 2020-10-29 17:21
For the path checkbox, the problem is this line in the intro model constructor, so pressing ResetAllButton will actually turn it back on:
```js
    // by default the Intro screen does not save samples
    this.saveSamplesProperty.set( false );
```

We need to provide default value rather than just set to false in constructor. And the the image is just missing a reset, sorry about that.

**Comment by jessegreenberg** [comment] 2020-10-29 17:25
Both cases fixed with above commits, will bring them to RC branch as well.

**Comment by jessegreenberg** [comment] 2020-11-09 18:09
Moved to 1.1 release branch.

**Closed** 2020-11-09 20:38 UTC
Labels: status:ready-for-qa, type:bug
